# Generated by Django 3.2.10 on 2022-05-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_cafeteria_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_office_owner',
        ),
        migrations.AddField(
            model_name='user',
            name='acc_type',
            field=models.CharField(choices=[('Resturent', 'Resturent'), ('Office', 'Office')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
