# Generated by Django 3.2.10 on 2022-05-18 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('booking_type', models.CharField(choices=[('Price Per Hour', 'Price Per Hour'), ('Price Per Person', 'Price Per Person'), ('Price Per Day', 'Price Per Day')], max_length=16)),
                ('booking_price', models.PositiveIntegerField()),
                ('booking_status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Not Available', 'Not Available')], max_length=15)),
                ('timing_days_available', models.CharField(max_length=20)),
                ('cafeteria', models.BooleanField()),
                ('cafeteria_description', models.TextField()),
                ('wifi', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Not Available', 'Not Available')], max_length=15)),
                ('sitting_details', models.TextField()),
                ('description', models.TextField()),
                ('add_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='resturent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
