# Generated by Django 3.2.10 on 2022-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturent',
            name='cafeteria_description',
        ),
        migrations.RemoveField(
            model_name='resturent',
            name='description',
        ),
        migrations.AddField(
            model_name='resturent',
            name='cafeteria_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resturent',
            name='resturent_other_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resturent',
            name='cafeteria',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=15),
        ),
    ]
