# Generated by Django 3.2.10 on 2022-05-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0002_auto_20220518_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturent',
            old_name='mobile',
            new_name='phone',
        ),
    ]
