# Generated by Django 3.2.10 on 2022-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0003_rename_mobile_resturent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturent',
            name='booking_type',
            field=models.CharField(choices=[('Per Hour', 'Per Hour'), ('Per Person', 'Per Person'), ('Per Day', 'Per Day')], max_length=16),
        ),
    ]
