# Generated by Django 3.2.10 on 2022-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0004_alter_resturent_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturent',
            name='timing_days_available',
            field=models.CharField(max_length=40),
        ),
    ]
