# Generated by Django 3.2.10 on 2022-05-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0005_alter_resturent_timing_days_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturent',
            name='image',
            field=models.ImageField(upload_to='resturents'),
        ),
        migrations.AlterField(
            model_name='resturent',
            name='resturent_other_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
